name: Check & fix styling

on: [push]

jobs:
    style:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
            -   uses: actions/checkout@v3
            -   name: Setup PHP with shared extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: '7.4'
                    extensions: json, mbstring, xml, ctype, tokenizer, opcache, zip, intl, bcmath
            -   name: Install Dependencies
                run: composer install --no-interaction
            -   name: Fix style
                uses: docker://oskarstark/php-cs-fixer-ga
                run: php vendor/bin/php-cs-fixer fix --allow-risky=yes
            -   name: Extract branch name
                shell: bash
                run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
                id: extract_branch
            -   name: Commit changes
                uses: stefanzweifel/git-auto-commit-action@v2.3.0
                with:
                    commit_message: Fix styling
                    branch: ${{ steps.extract_branch.outputs.branch }}
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}